name: orb-test
channels:
  - astropy
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py37_0
  - argon2-cffi=20.1.0=py37h8f50634_1
  - asdf=2.4.2=py_1
  - astropy=4.0.1.post1=py37h7b6447c_1
  - astroquery=0.4.1=pyh9f0ad1d_0
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - beautifulsoup4=4.9.1=py37_0
  - blas=1.0=mkl
  - bleach=3.1.5=pyh9f0ad1d_0
  - blosc=1.19.0=hd408876_0
  - bottleneck=1.3.2=py37heb32a55_1
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.5.0=py_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - cycler=0.10.0=py37_0
  - cython=0.29.21=py37he6710b0_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask-core=2.20.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.2=py_0
  - docutils=0.16=py37_1
  - entrypoints=0.3=py37_0
  - expat=2.2.9=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.65.0=h3eb4bd4_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - gwcs=0.13.0=py_0
  - h5py=2.10.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - html5lib=1.1=py_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.3.4=py37h43977f1_0
  - ipython=5.8.0=py37_1
  - ipython_genutils=0.2.0=py_1
  - jeepney=0.4.3=py_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py37_1
  - jupyter_client=6.1.6=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyterlab=2.2.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - keyring=21.2.1=py37_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - lzo=2.10=h7b6447c_2
  - markupsafe=1.1.1=py37h8f50634_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hef1b27d_0
  - mistune=0.8.4=py37h8f50634_1001
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - mock=4.0.2=py_0
  - more-itertools=8.4.0=py_0
  - nbconvert=5.6.1=py37hc8dfbb8_1
  - nbformat=5.0.7=py_0
  - nbsphinx=0.7.1=pyh9f0ad1d_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - notebook=6.1.1=py37hc8dfbb8_0
  - numexpr=2.7.1=py37h423224d_0
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h516909a_1
  - packaging=20.4=py_0
  - pandas=1.0.5=py37h0573a6f_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - photutils=0.7.2=py37h516909a_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pluggy=0.13.1=py37_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.6.0=py_1001
  - py=1.9.0=py_0
  - pycparser=2.20=py_2
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyregion=2.0=py37hc1659b7_1001
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - pytables=3.6.1=py37h71ec239_0
  - pytest=5.4.3=py37_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - pyzmq=19.0.2=py37hac76be4_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - scikit-image=0.16.2=py37h0573a6f_0
  - scikit-learn=0.23.1=py37h423224d_0
  - scipy=1.5.0=py37h0b6359f_0
  - secretstorage=3.1.2=py37_1
  - semantic_version=2.6.0=py37_0
  - send2trash=1.5.0=py_0
  - setuptools=49.2.0=py37_0
  - simplegeneric=0.8.1=py_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - snappy=1.1.8=he6710b0_0
  - snowballstemmer=2.0.0=py_0
  - soupsieve=2.0.1=py_0
  - sphinx=3.1.2=py_0
  - sphinx_rtd_theme=0.5.0=pyh9f0ad1d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.32.3=h62c20be_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - urllib3=1.25.9=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.2=he1b5a44_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - fpdf==1.7.2
    - gvar==9.2
    - lsqfit==11.2
prefix: /home/thomas/miniconda2/envs/orb-test

